import io
import os
from datetime import date
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.http import FileResponse, Http404
from django.conf import settings
from django.contrib import messages
from apps.regions.models import Region
from apps.water_data.models import WaterMeasurement
from apps.predictions.models import WaterPrediction
from .models import Report

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def generate_pdf_report(report, region, measurements, predictions):
    """Generate a PDF report and return its bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=18,
        spaceAfter=12,
    )
    story.append(Paragraph(f'AquaGuard AI — {report.title}', title_style))
    story.append(Paragraph(f'Region: {region.name}, {region.state}', styles['Normal']))
    story.append(Paragraph(f'Generated: {date.today().strftime("%B %d, %Y")}', styles['Normal']))
    story.append(Spacer(1, 0.5 * cm))

    # Summary
    story.append(Paragraph('Executive Summary', styles['Heading2']))
    story.append(Paragraph(report.summary or 'No summary available.', styles['Normal']))
    story.append(Spacer(1, 0.5 * cm))

    # Latest Water Measurements table
    if measurements:
        story.append(Paragraph('Recent Water Measurements (Last 10 Days)', styles['Heading2']))
        table_data = [['Date', 'Reservoir %', 'Rainfall (mm)', 'Consumption (MLD)', 'Groundwater (m)']]
        for m in measurements[:10]:
            table_data.append([
                str(m.date),
                f'{m.reservoir_level:.1f}%',
                f'{m.rainfall_mm:.1f}',
                f'{m.water_consumption_mld:.1f}',
                f'{m.groundwater_level_m:.1f}',
            ])
        table = Table(table_data, colWidths=[3 * cm, 3 * cm, 3 * cm, 3.5 * cm, 3.5 * cm])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3b82d4')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f7f8fa')]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('PADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(table)
        story.append(Spacer(1, 0.5 * cm))

    # Predictions
    if predictions:
        story.append(Paragraph('Current Risk Predictions', styles['Heading2']))
        for pred in predictions[:3]:
            story.append(Paragraph(
                f'• {pred.horizon_days}-day horizon: <b>{pred.risk_level}</b> risk '
                f'({pred.risk_probability * 100:.0f}% probability). '
                f'Predicted reservoir level: {pred.predicted_reservoir_level:.1f}%.',
                styles['Normal'],
            ))
        story.append(Spacer(1, 0.5 * cm))

    # Footer
    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph(
        'This report was generated by AquaGuard AI. Data is for planning purposes only.',
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey),
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer


class ReportListView(View):
    template_name = 'reports/report_list.html'

    def get(self, request):
        reports = Report.objects.select_related('region', 'user').order_by('-generated_at')
        return render(request, self.template_name, {'reports': reports})


class GenerateReportView(View):
    template_name = 'reports/generate_report.html'

    def get(self, request):
        regions = Region.objects.filter(is_active=True)
        return render(request, self.template_name, {'regions': regions})

    def post(self, request):
        region_id = request.POST.get('region')
        report_type = request.POST.get('report_type', 'water_summary')
        region = get_object_or_404(Region, pk=region_id)

        measurements = WaterMeasurement.objects.filter(region=region).order_by('-date')[:30]
        predictions = WaterPrediction.objects.filter(region=region).order_by('-prediction_date')[:3]

        # Build summary text
        avg_level = (
            sum(m.reservoir_level for m in measurements) / len(measurements)
            if measurements else 0
        )
        latest_risk = predictions[0].risk_level if predictions else 'N/A'
        summary = (
            f'This report covers water data for {region.name}, {region.state}. '
            f'Average reservoir level over the analysis period: {avg_level:.1f}%. '
            f'Current risk assessment: {latest_risk}. '
            f'Population served: {region.population:,}.'
        )

        # user is null=True — set to authenticated user if available, else None
        report = Report.objects.create(
            region=region,
            user=request.user if request.user.is_authenticated else None,
            title=f'{region.name} Water Status Report',
            report_type=report_type,
            summary=summary,
            parameters={'region_id': region_id, 'report_type': report_type},
        )

        if REPORTLAB_AVAILABLE:
            pdf_buffer = generate_pdf_report(report, region, list(measurements), list(predictions))
            filename = f'report_{report.pk}_{region.name.lower().replace(" ", "_")}.pdf'
            media_reports_dir = os.path.join(settings.MEDIA_ROOT, 'reports')
            os.makedirs(media_reports_dir, exist_ok=True)
            file_path = os.path.join(media_reports_dir, filename)
            with open(file_path, 'wb') as f:
                f.write(pdf_buffer.read())
            report.file_path = f'reports/{filename}'
            report.save(update_fields=['file_path'])
            messages.success(request, f'Report "{report.title}" generated successfully.')
        else:
            messages.warning(request, 'Report saved but PDF generation unavailable (reportlab not installed).')

        return redirect('reports:list')


class DownloadReportView(View):
    def get(self, request, pk):
        report = get_object_or_404(Report, pk=pk)
        if not report.file_path:
            raise Http404('No file available for this report.')
        file_full_path = os.path.join(settings.MEDIA_ROOT, str(report.file_path))
        if not os.path.exists(file_full_path):
            raise Http404('Report file not found on disk.')
        return FileResponse(
            open(file_full_path, 'rb'),
            as_attachment=True,
            filename=os.path.basename(file_full_path),
            content_type='application/pdf',
        )
