# Generated by Django 6.0.7 on 2026-10-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reservoir_level', models.FloatField(help_text='Reservoir fill percentage (0-100)')),
                ('reservoir_capacity_mcm', models.FloatField(help_text='Total reservoir capacity in million cubic meters')),
                ('current_storage_mcm', models.FloatField(help_text='Current storage in million cubic meters')),
                ('rainfall_mm', models.FloatField(help_text='Daily rainfall in millimeters')),
                ('water_consumption_mld', models.FloatField(help_text='Water consumption in million litres per day')),
                ('groundwater_level_m', models.FloatField(help_text='Groundwater level in meters below ground')),
                ('inflow_mcm', models.FloatField(help_text='Daily inflow in million cubic meters')),
                ('outflow_mcm', models.FloatField(help_text='Daily outflow in million cubic meters')),
                ('is_demo_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_measurements', to='regions.region')),
            ],
            options={
                'verbose_name': 'Water Measurement',
                'verbose_name_plural': 'Water Measurements',
                'ordering': ['-date'],
                'unique_together': {('region', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_celsius', models.FloatField()),
                ('humidity_percent', models.FloatField()),
                ('wind_speed_kmh', models.FloatField()),
                ('is_demo_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_measurements', to='regions.region')),
            ],
            options={
                'verbose_name': 'Weather Measurement',
                'verbose_name_plural': 'Weather Measurements',
                'ordering': ['-date'],
                'unique_together': {('region', 'date')},
            },
        ),
    ]
